# https://golangci-lint.run/docs/configuration/file/
version: "2"

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - depguard
    - err113
    - noinlineerr

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - swaggo

run:
  timeout: 5m
  tests: false
